<a href="https://colab.research.google.com/github/balluk/deeplearning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [ ]:
import torch

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Introduction to Tensors

## creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

In [ ]:
# Create a random tensors of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1267, 0.1765, 0.8034, 0.5325],
        [0.5531, 0.5650, 0.8144, 0.5307],
        [0.2495, 0.4977, 0.1935, 0.2471]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and ones

In [ ]:
zeros = torch.zeros((3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones((3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
### Creating a range of tensors and tensors-like
one_to_ten = torch.arange(start=0,end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [ ]:
floattype = torch.tensor([3.0, 6.0, 9.0] , dtype=None, device=None, requires_grad=False)

In [ ]:
floattype.dtype

torch.float32

In [ ]:
float_16_tensor = floattype.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
# create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [ ]:
tensor * 10


tensor([10, 20, 30])

In [ ]:
# Try out OyTorch inbuilt
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
# Matrix multiplication (dot product)
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [ ]:
torch.matmul(x , x)

tensor(14)

In [ ]:
torch.matmul(torch.rand(10,2), torch.rand(2,10))

tensor([[0.7418, 0.5577, 0.7341, 1.2871, 0.7592, 0.5504, 0.5434, 0.9394, 1.4136,
         0.1734],
        [0.1829, 0.1346, 0.1828, 0.2899, 0.1541, 0.1377, 0.1283, 0.2223, 0.3196,
         0.0404],
        [0.2828, 0.2028, 0.2861, 0.3976, 0.1771, 0.2165, 0.1878, 0.3266, 0.4408,
         0.0581],
        [0.2841, 0.2127, 0.2816, 0.4847, 0.2808, 0.2113, 0.2064, 0.3569, 0.5327,
         0.0657],
        [0.7036, 0.5168, 0.7041, 1.1055, 0.5809, 0.5303, 0.4914, 0.8520, 1.2192,
         0.1545],
        [0.5695, 0.3945, 0.5850, 0.6684, 0.1969, 0.4454, 0.3506, 0.6130, 0.7482,
         0.1055],
        [0.5646, 0.4146, 0.5649, 0.8862, 0.4651, 0.4256, 0.3941, 0.6833, 0.9774,
         0.1239],
        [0.8654, 0.6421, 0.8618, 1.4212, 0.7887, 0.6479, 0.6172, 1.0687, 1.5644,
         0.1954],
        [0.0560, 0.0495, 0.0508, 0.1673, 0.1419, 0.0366, 0.0556, 0.0947, 0.1806,
         0.0192],
        [0.3502, 0.2420, 0.3600, 0.4062, 0.1153, 0.2742, 0.2146, 0.3753, 0.4550,
         0.0645]])

## Find the min, max. mean, sum etc (tensor aggregation)

In [ ]:
x = torch.arange(0, 100, 10)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [ ]:
x.max()

tensor(90)

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.sum()

tensor(450)

In [ ]:
## Finding the positional min and max
x.argmin()


tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[0]

tensor(0)

In [ ]:
x[9]

tensor(90)

In [ ]:
## Reshaoing, stacking, squeezing and unsqueezing tensors
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add an extra dimension (Reshape)
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# change the view
z = x.view(1, 9)
z.shape

torch.Size([1, 9])

In [ ]:
x = torch.arange(1,10,1)

In [ ]:
x_reshaped = x.reshape(1,3,3)

In [ ]:
x_reshaped

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x_reshaped[0,2,0]

tensor(7)

In [ ]:
x_reshaped[0,0]

tensor([1, 2, 3])

In [ ]:
x_reshaped.shape

torch.Size([1, 3, 3])

In [ ]:
x_reshaped[:,1]

tensor([[4, 5, 6]])

In [ ]:
x_reshaped[:,:,0]

tensor([[1, 4, 7]])

In [ ]:
x_reshaped[:,:0]

tensor([], size=(1, 0, 3), dtype=torch.int64)

In [ ]:
x_reshaped[:,:0,1]

tensor([], size=(1, 0), dtype=torch.int64)

In [ ]:
## PyTorch Reproducibility i.e. removing the randomness from randomness
## By using a common random seed
RANDOM_SEED = 77
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)



tensor([[0.2919, 0.2857, 0.4021, 0.4645],
        [0.9503, 0.2564, 0.6645, 0.8609],
        [0.3538, 0.3347, 0.7285, 0.5794]])
tensor([[0.2919, 0.2857, 0.4021, 0.4645],
        [0.9503, 0.2564, 0.6645, 0.8609],
        [0.3538, 0.3347, 0.7285, 0.5794]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
